export { default as Login } from './Login/Login'
export { default as Register } from './Register/Register'
export { default as Home } from './Home/Home'
export { default as Error } from './Error/Error'
export { default as RealEstate } from './RealEstate/RealEstate'
// export { default as Contacts } from './Contacts/Contacts'
// export { default as About } from './About/About'
export { default as Office } from './Office/Office'
// export { default as AddHome } from './AddHome/AddHome'
export { default as Contact } from './Contact/Contact'
export { default as Display } from './Display/Display'
export { default as PropertyDetails } from './PropertyDetails/PropertyDetail'
export { default as OfficeList } from './OfficeList/OfficeList'
export { default as Dashboard } from './Dashboard/Dashboard'
export { default as Complaints } from './Complaints/Complaints'
export { default as OfficeManagement } from './OfficeManagement/OfficeManagement'
export { default as LocationManagement } from './LocationManagement/LocationManagement'
export { default as Profile } from './Profile/Profile'
export { default as ServicesManagement } from './ServicesManagement/ServicesManagement'
export { default as VerificationForm } from './VerificationForm/VerificationForm'
export { default as VerificationsList } from './VerificationsList/VerificationsList'
export { default as AdminLogin } from './AdminLogin/AdminLogin'
export { default as RegisterPage } from './RegisterPage/RegisterPage'
